// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2E47hEKmqJQ749LPHVRbzzadRQPgxVOs',
    appId: '1:637451854825:web:e41c611483c286f403e178',
    messagingSenderId: '637451854825',
    projectId: 'simplelogin-2c67d',
    authDomain: 'simplelogin-2c67d.firebaseapp.com',
    storageBucket: 'simplelogin-2c67d.appspot.com',
    measurementId: 'G-TQ5F2CPFNS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhmUms2LXgbunRoOVDtWMfjnF86zr92IY',
    appId: '1:637451854825:android:e87d5a973fef3b6303e178',
    messagingSenderId: '637451854825',
    projectId: 'simplelogin-2c67d',
    storageBucket: 'simplelogin-2c67d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY_EivtlbnTCLWG74i3QwG8q0Acp52iE8',
    appId: '1:637451854825:ios:a9c0667e541a05ab03e178',
    messagingSenderId: '637451854825',
    projectId: 'simplelogin-2c67d',
    storageBucket: 'simplelogin-2c67d.appspot.com',
    iosClientId: '637451854825-huia22ulfreoovimej9f6s8kehv3q8oe.apps.googleusercontent.com',
    iosBundleId: 'com.example.simpleLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCY_EivtlbnTCLWG74i3QwG8q0Acp52iE8',
    appId: '1:637451854825:ios:a9c0667e541a05ab03e178',
    messagingSenderId: '637451854825',
    projectId: 'simplelogin-2c67d',
    storageBucket: 'simplelogin-2c67d.appspot.com',
    iosClientId: '637451854825-huia22ulfreoovimej9f6s8kehv3q8oe.apps.googleusercontent.com',
    iosBundleId: 'com.example.simpleLogin',
  );
}
